import tensorflow as tf

cfg = tf.contrib.training.HParams(
    # cfg
    debug=True,
    bn=True,
    debug_dir='./out/fillin_answer_less4words_1_31_img/debug',
    # out_dir='./out/fillin_answer_less4words_1_31_img',
    # data_set='./data_set/fillin_answer_less4words_1_31_img',
    out_dir='./out/HANG_RECG3',
    data_set='./data_set/HANG_RECG3',
    # data_set='E:\\yu_collection\\hang_recg_gene_Anan\\Anan\\fillin_answer_less4words_1_31_img',
    # out_dir='E:\\yu_collection\\hang_recg_gene_Anan\\Anan\\fillin_answer_less4words_1_31_img',
    ano_data_set='ano',
    imgFolderName='jpg',
    tgt_vocab_file='recg.vocb',
    train_src_dataset='train.ind',
    train_tgt_dataset='train.recg',
    train_tf_filename='train.tfrecords',
    vaild_src_dataset='vaild.ind',
    vaild_tgt_dataset='vaild.recg',
    vaild_tf_filename='vaild.tfrecords',
    # load_preTrain_model_folder='./out/fillin_answer_less4words_1_31_img/2018_02_06_22_14_24',
    # load_preTrain_model_name='checkPoint.model-120000',
    load_preTrain_model_folder=None,
    load_preTrain_model_name=None,
    unk="<unk>",
    sos="<s>",
    eos="</s>",
    src_fixed_height=96,
    src_max_len=1920,
    tgt_max_len=50,
    allow_grow_ratio=1,
    cnn_strike=24,
    num_buckets=0,
    default_bucket_width=10,

    rnn_input_dimensions=32,
    rnn_hidden_size=128,
    attention_size=32,
    coverage_size=32,
    tgt_embedding_size=32,

    outer_batch_size=None,
    batch_size=1,
    keep_prob=0.8,
    # train param
    startLr=0.1,
    decay_steps=5000,
    decay_rate=0.96,
    epochs=800,
    each_steps=300,
    print_frq=20,
    summary_frq=50,
    val_frq=1,
    save_frq=50,
    val_steps=40,
    test_show_size=4,
)
